CREATE TABLE LOAI_MON (
    MaLoai CHAR(10) PRIMARY KEY,
    TenLoai VARCHAR(50) NOT NULL UNIQUE
);


CREATE TABLE MON_AN (
    MaMon CHAR(10) PRIMARY KEY,
    TenMon VARCHAR(100) NOT NULL,
    Gia DECIMAL(10,2) NOT NULL CHECK (Gia >= 0),
    MaLoai CHAR(10) NOT NULL,
    CONSTRAINT FK_MON_AN_LOAI_MON FOREIGN KEY (MaLoai) REFERENCES LOAI_MON(MaLoai)
);


CREATE TABLE KHACH_HANG (
    MaKH CHAR(10) PRIMARY KEY,
    TenKH VARCHAR(100) NOT NULL,
    SDT CHAR(10) UNIQUE
);


CREATE TABLE NHAN_VIEN (
    MaNV CHAR(10) PRIMARY KEY,
    TenNV VARCHAR(100) NOT NULL,
    CaLam VARCHAR(20)
);


CREATE TABLE MAY_ORDER (
    MaMay CHAR(10) PRIMARY KEY,
    ViTri VARCHAR(100) NOT NULL,
    TrangThai VARCHAR(30) NOT NULL DEFAULT 'Hoat dong',
    CONSTRAINT CHK_MAY_ORDER_TrangThai CHECK (TrangThai IN ('Hoat dong', 'Bao tri', 'Loi'))
);


CREATE TABLE PHIEN_ORDER (
    MaPhien CHAR(10) PRIMARY KEY,
    MaKH CHAR(10) NOT NULL,
    MaMay CHAR(10) NOT NULL,
    ThoiGianBatDau DATETIME NOT NULL DEFAULT GETDATE(),
    ThoiGianKetThuc DATETIME,
    TrangThai VARCHAR(20) NOT NULL DEFAULT 'DangHoatDong',
    CONSTRAINT FK_PHIEN_ORDER_KHACH_HANG FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH),
    CONSTRAINT FK_PHIEN_ORDER_MAY_ORDER FOREIGN KEY (MaMay) REFERENCES MAY_ORDER(MaMay)
);


CREATE INDEX idx_may_trangthai ON PHIEN_ORDER(MaMay, TrangThai);


CREATE TABLE VAI_TRO (
    MaVaiTro CHAR(10) PRIMARY KEY,
    TenVaiTro VARCHAR(50) NOT NULL UNIQUE
);


CREATE TABLE HOA_DON (
    MaHD CHAR(10) PRIMARY KEY,
    NgayLap DATETIME NOT NULL DEFAULT GETDATE(),
    MaNV CHAR(10) NOT NULL,
    MaPhien CHAR(10) NOT NULL,
    TongTien DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (TongTien >= 0),
    PhuongThucTT VARCHAR(50),
    TrangThai VARCHAR(30) NOT NULL DEFAULT 'Pending',
    CONSTRAINT FK_HOA_DON_NHAN_VIEN FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV),
    CONSTRAINT FK_HOA_DON_PHIEN_ORDER FOREIGN KEY (MaPhien) REFERENCES PHIEN_ORDER(MaPhien)
);


CREATE INDEX idx_hoa_don_ngaylap ON HOA_DON(NgayLap);
CREATE INDEX idx_hoa_don_maphien ON HOA_DON(MaPhien);


CREATE TABLE CHI_TIET_HOA_DON (
    MaHD CHAR(10),
    MaMon CHAR(10),
    SoLuong INT NOT NULL DEFAULT 1 CHECK (SoLuong > 0),
    DonGia DECIMAL(10,2) NOT NULL CHECK (DonGia >= 0),
    CONSTRAINT PK_CHI_TIET_HOA_DON PRIMARY KEY (MaHD, MaMon),
    CONSTRAINT FK_CHI_TIET_HOA_DON_HOA_DON FOREIGN KEY (MaHD) REFERENCES HOA_DON(MaHD) ON DELETE CASCADE,
    CONSTRAINT FK_CHI_TIET_HOA_DON_MON_AN FOREIGN KEY (MaMon) REFERENCES MON_AN(MaMon)
);


CREATE TABLE TAI_KHOAN (
    MaTK CHAR(10) PRIMARY KEY,
    TenDN VARCHAR(50) UNIQUE NOT NULL,
    MatKhau CHAR(60) NOT NULL,
    MaVaiTro CHAR(10) NOT NULL,
    MaKH CHAR(10) NULL,
    MaNV CHAR(10) NULL,
    NguoiTao CHAR(10),
    NgayTao DATETIME NOT NULL DEFAULT GETDATE(),
    TrangThai VARCHAR(20) NOT NULL DEFAULT 'Active',
    CONSTRAINT FK_TAI_KHOAN_VAI_TRO FOREIGN KEY (MaVaiTro) REFERENCES VAI_TRO(MaVaiTro),
    CONSTRAINT FK_TAI_KHOAN_KHACH_HANG FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH),
    CONSTRAINT FK_TAI_KHOAN_NHAN_VIEN FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV),
    CONSTRAINT FK_TAI_KHOAN_NGUOI_TAO FOREIGN KEY (NguoiTao) REFERENCES NHAN_VIEN(MaNV),
    CONSTRAINT CHK_TAI_KHOAN_User CHECK (
        (MaKH IS NOT NULL AND MaNV IS NULL) OR 
        (MaKH IS NULL AND MaNV IS NOT NULL)
    )
);
